"""fix settings column names

Revision ID: 3babb05279b3
Revises: b166034a7d24
Create Date: 2026-07-27 09:09:41.751605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3babb05279b3'
down_revision = 'b166034a7d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dietary_preference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unit_system', sa.String(), nullable=True))
        batch_op.drop_column('unit_systems')
        batch_op.drop_column('dietary_preferences')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dietary_preferences', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unit_systems', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('unit_system')
        batch_op.drop_column('dietary_preference')

    # ### end Alembic commands ###
